micronaut:
  application:
    name: relatorioService
  server:
    port: -1
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: kafka-server:9092
mongodb:
  uri: 'mongodb://root:e296cd9f@ms-mongo:27017/admin'
consul:
  client:
    registration:
      enabled: true
    defaultZone: "ms-consul:8500"
